/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackIndex: typeof import('./../layout/components/BackIndex.vue')['default']
    BadReview: typeof import('./../pages/components/BadReview.vue')['default']
    BadReviewLatest: typeof import('./../pages/components/BadReviewLatest.vue')['default']
    BadReviewList: typeof import('./../pages/components/BadReviewList.vue')['default']
    BadReviewStatistics: typeof import('./../pages/components/BadReviewStatistics.vue')['default']
    ClassCompared: typeof import('./../pages/components/ClassCompared.vue')['default']
    ClassInfo: typeof import('./../pages/components/ClassInfo.vue')['default']
    Header: typeof import('./../layout/components/Header.vue')['default']
    NumberOfSessions: typeof import('./../pages/components/NumberOfSessions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SatisfactionRanking: typeof import('./../pages/components/SatisfactionRanking.vue')['default']
    SessionsDuration: typeof import('./../pages/components/SessionsDuration.vue')['default']
    SessionsRanking: typeof import('./../pages/components/SessionsRanking.vue')['default']
    StuQuesRank: typeof import('./../pages/components/StuQuesRank.vue')['default']
    StuQuesRanking: typeof import('./../pages/components/StuQuesRanking.vue')['default']
    Time: typeof import('./../layout/components/Time.vue')['default']
    Times: typeof import('./../layout/components/Times.vue')['default']
    UCard: typeof import('./../components/UCard.vue')['default']
    UCircleProgress: typeof import('./../components/UCircleProgress.vue')['default']
    Weather: typeof import('./../layout/components/Weather.vue')['default']
    YearUsageData: typeof import('./../pages/components/YearUsageData.vue')['default']
    YesterdayData: typeof import('./../pages/components/YesterdayData.vue')['default']
  }
}
